### ISSUE TITLE
사용법(?)에 대한 좀더 상세한 설명이 필요합니다...

### ISSUE THREAD

**Issue by kimkang79** [ax5ui/ax5ui-uploader#1]
![11](https://cloud.githubusercontent.com/assets/12708061/25831856/cb2694d8-34a1-11e7-91b3-ea31e6ac7cc4.png)
========================================================
![22](https://cloud.githubusercontent.com/assets/12708061/25831877/f75c2f5e-34a1-11e7-9760-e4071efdd5cb.png)
Thumbnail Uploader를 이용하여 파일업로드 기능을 붙여보려 합니다.
Demo페이지에 있는 소스 그대로 C&P 하였고
위와 같이 "action"의 url만 변경하였습니다.
위의 url로 호출되는 Controller는 아래 그림이구요.

====질문!====
브라우저의 개발자도구를 사용하여 처리과정을 살펴보니,
Demo화면에서는 json형태로 업로드 파일에대한 정보를 확인 할 수 있는데(아래그림)
![333](https://cloud.githubusercontent.com/assets/12708061/25832038/12415e60-34a3-11e7-9d53-633d54cdca1b.png)
저의 개발환경에서는 파일정보가 하나도 보이지 않습니다.
Controller 부분에서 받는방법이 잘못된것인지... 일주일 가까이 헤메고 있네요.
(서교동에 있다는 사무실이라도 찾아가야 하나 싶은 생각이.. ㅠㅠ)

혹시 잘못된 원인파악이나, Controller쪽의 샘플을 제공 받을 수 있을까요?

**Comment by thomasJang** [comment]
관련 소스스를 @aeei 님께서 공유해주실 것으로 기대합니다.

**Comment by kimkang79** [comment]
네 감사합니다~ 범위를 벗어난듯한 질문에도 응답을 주시는군요 ㅠ_ㅠ
@aeei 님의 자료 기다리고 있겠습니다!
