### ISSUE TITLE
파일업로드 시, 파라메터 추가 방법 문의

### ISSUE THREAD

**Issue by kimkang79** [ax5ui/ax5ui-uploader#2]
ax5ui-uploader에서는 파일업로드시 POST방식을 사용하는것으로 알고 있는데요,
파라메터를 추가하고 싶은경우 어떻게 추가해야 하는지 모르겠습니다.
![111](https://cloud.githubusercontent.com/assets/12708061/26448843/47f18456-418a-11e7-8d96-0f1c726e1498.png)
위의 점선부분에서 가능하지 않을까~라는 막연한 생각은 들지만 방법을 찾을수가 없네요.

**Comment by thomasJang** [comment]
예제 문서에서 제가 설명을 빼먹었네요..

https://github.com/ax5ui/ax5ui-uploader/blob/master/test/index.html#L26
여기 참고해주세요.

**Comment by kimkang79** [comment]
저의 추측은 민망하게 빗나갔지만~
우왕~감사합니다 ^^
