### ISSUE TITLE
파일업로드시 Upload form 표시 문의

### ISSUE THREAD

**Issue by kimkang79** [ax5ui/ax5ui-uploader#3]
안녕하세요.
파일업로드 후 업로된 파일의 표현이 이상하게 나오고 있어서 문의 드립니다.
https://github.com/ax5ui/ax5ui-uploader/blob/master/test/api/fileUpload.php
이곳의 샘플을 보니, json데이터 형태로 업로드 정보를 return해줘야 하는것 같아서 동일하게 처리했다고 생각했는데, 아래와 같이 나오고 있습니다.
![before](https://cloud.githubusercontent.com/assets/12708061/26526375/d9b1c34e-43b3-11e7-8940-1b1572854943.png)

** 파일업로드창을 새로고침 하면 아래와 같이 정상적으로 보여집니다.
![after](https://cloud.githubusercontent.com/assets/12708061/26526380/f6813c34-43b3-11e7-8e19-f4d876ee9051.png)

이해를 잘 못하고 있는건지...어느부분을 살펴봐야 할지 조언 부탁드립니다.

**Comment by thomasJang** [comment]
![image](https://cloud.githubusercontent.com/assets/5884902/26528100/d636b2d6-43dd-11e7-8f5b-7b1635f83267.png)

php 샘플은 좀 오래된 버전 이라서요. return json을 이걸로 하셔야 되겠습니다.
그리고 저희가 쓰는 JAVA버전을 공유 해드리려고 링크는 만들었는데. 
https://gist.github.com/thomasJang/aec2fd1c30d2e8de911103ec344244b7
이게 좀 단순한 형태는 아니라. 도움이 되실 지 모르겠네요.

**Comment by kimkang79** [comment]
감사합니다~!
제공 해 주신 링크를 참고해서 조금 더 연구 해 봐야 할것 같습니다.
소스를 훑어보니 많은 도움이 될것 같습니다 ^^

**Comment by kimkang79** [comment]
성공했습니다~! ^^
제공해주신 링크의 AX5File을 이용해서 Controller에서 리턴값 처리 했습니다.
감사합니다~
